workspace:
  base: /drone/src
  path: /usr/local/src/github.com/qnib/go-httpcheck

pipeline:
  alpine:
    image: qnib/alplain-golang
    commands:
      - go build -o go-httpcheck_Alpine
  x86:
      image: qnib/uplain-golang
      commands:
        - go build -o go-httpcheck_x86
